In [60]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import seaborn as sns

In [118]:
raw_data = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/epi_r.csv')

In [93]:
raw_data.head()

title rating  calories  protein  \
0              Lentil, Apple, and Turkey Wrap     2.5     426.0     30.0   
1  Boudin Blanc Terrine with Red Onion Confit   4.375     403.0     18.0   
2                Potato and Fennel Soup Hodge    3.75     165.0      6.0   
3             Mahi-Mahi in Tomato Olive Sauce     5.0       NaN      NaN   
4                    Spinach Noodle Casserole   3.125     547.0     20.0   

    fat  sodium  #cakeweek  #wasteless  22-minute meals  3-ingredient recipes  \
0   7.0   559.0        0.0         0.0              0.0                   0.0   
1  23.0  1439.0        0.0         0.0              0.0                   0.0   
2   7.0   165.0        0.0         0.0              0.0                   0.0   
3   NaN     NaN        0.0         0.0              0.0                   0.0   
4  32.0   452.0        0.0         0.0              0.0                   0.0   

   ...  snack week  turkey  rating_0.0  rating_1.25  rating_1.875  rating_2.5  \
0  ...         0.0     1.0           0            0             0           1   
1  ...         0.0     0.0           0            0             0           0   
2  ...         0.0     0.0           0            0             0           0   
3  ...         0.0     0.0           0            0             0           0   
4  ...         0.0     0.0           0            0             0           0   

   rating_3.125  rating_3.75  rating_4.375  rating_5.0  
0             0            0             0           0  
1             0            0             1           0  
2             0            1             0           0  
3             0            0             0           1  
4             1            0             0           0  

[5 rows x 688 columns]

In [12]:
list(raw_data.columns)

['title',
 'rating',
 'calories',
 'protein',
 'fat',
 'sodium',
 '#cakeweek',
 '#wasteless',
 '22-minute meals',
 '3-ingredient recipes',
 '30 days of groceries',
 'advance prep required',
 'alabama',
 'alaska',
 'alcoholic',
 'almond',
 'amaretto',
 'anchovy',
 'anise',
 'anniversary',
 'anthony bourdain',
 'aperitif',
 'appetizer',
 'apple',
 'apple juice',
 'apricot',
 'arizona',
 'artichoke',
 'arugula',
 'asian pear',
 'asparagus',
 'aspen',
 'atlanta',
 'australia',
 'avocado',
 'back to school',
 'backyard bbq',
 'bacon',
 'bake',
 'banana',
 'barley',
 'basil',
 'bass',
 'bastille day',
 'bean',
 'beef',
 'beef rib',
 'beef shank',
 'beef tenderloin',
 'beer',
 'beet',
 'bell pepper',
 'berry',
 'beverly hills',
 'birthday',
 'biscuit',
 'bitters',
 'blackberry',
 'blender',
 'blue cheese',
 'blueberry',
 'boil',
 'bok choy',
 'bon appétit',
 'bon app��tit',
 'boston',
 'bourbon',
 'braise',
 'bran',
 'brandy',
 'bread',
 'breadcrumbs',
 'breakfast',
 'brie',
 'brine',
 'brisk

In [114]:
raw_data.rating.describe()

count     20052
unique        8
top       4.375
freq       8019
Name: rating, dtype: object

In [15]:
null_count = raw_data.isnull().sum()
null_count[null_count>0]

calories    4117
protein     4162
fat         4183
sodium      4119
dtype: int64

## First Model

in this first model we run the model after converting the target variable into a binary variable with values equal or more than 3.75 are good (1) and the other values are bad (0). In this model we condiser all the feature except the features with null values

In [119]:
from sklearn.svm import SVC
svc = SVC()
X = raw_data.drop(['rating', 'title', 'calories', 'protein', 'fat', 'sodium'], 1).sample(frac=0.3, replace=True, random_state=1)
Y = raw_data.rating.apply(lambda x:1 if x>= 3.75 else 0).sample(frac=0.3, replace=True, random_state=1)
svc.fit(X,Y)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [122]:
svc.score(X, Y)

0.788563829787234

In [123]:
from sklearn.model_selection import cross_val_score
cross_val_score(svc, X, Y, cv=5)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarni

array([0.78820598, 0.78820598, 0.78886118, 0.78886118, 0.78868552])

Not very good but better than runing the model as svr as shown in the example.

## Second Model

In this model, all features will be considered. the null values rows will be dropped from the dataframe

In [124]:
raw_data2 = raw_data.dropna()

In [131]:
svc = SVC()
X2 = raw_data2.drop(['rating', 'title'], 1).sample(frac=0.3, replace=True, random_state=1)
Y2 = raw_data2.rating.apply(lambda x:1 if x>= 3.75 else 0).sample(frac=0.3, replace=True, random_state=1)
svc.fit(X2,Y2)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [132]:
svc.score(X2, Y2)

0.8579533515444421

In [133]:
cross_val_score(svc, X2, Y2, cv=5)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarni

array([0.81007345, 0.81302521, 0.81302521, 0.81808623, 0.80967403])

The model is much better than the first model which shows the importance of the new features

## Third Model

in this model we will consider the top 30 features only. These features will be choosen using "feature importances" from random forest clasfier model

In [156]:
from sklearn import ensemble
rfc = ensemble.RandomForestClassifier()
X3 = pd.get_dummies(X2)
cross_val_score(rfc, X3, Y2, cv=5)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: F

array([0.85519412, 0.85189076, 0.84348739, 0.85173502, 0.84121977])

In [161]:
raw_data3 = pd.DataFrame()
raw_data3['score'] = rfc.fit(X3,Y2).feature_importances_
raw_data3['feature'] = X3.columns

In [162]:
importance = importance.sort_values(by='score', ascending=False)
importance.head()

score      feature
3   0.058073       sodium
0   0.048441     calories
1   0.047431      protein
2   0.046938          fat
61  0.013259  bon appétit

In [163]:
important_features = importance['feature'].iloc[0:30]
important_features = important_features.tolist()

In [172]:
raw_data4 = pd.DataFrame()
X4 = raw_data2.drop(['rating', 'title'], 1)
for feat in important_features:
    raw_data4[feat] = X4[feat]

In [174]:
X5 = raw_data4.sample(frac=0.3, replace=True, random_state=1)
Y5 = raw_data2.rating.apply(lambda x: 1 if x >= 3.75 else 0).sample(frac=0.3, replace=True, random_state=1)
svc.fit(X5,Y5)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [175]:
svc.score(X5,Y5)

0.9773061567556209

In [176]:
cross_val_score(svc, X5, Y5, cv=5)

C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\rabia\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarni

array([0.85099685, 0.85189076, 0.84768908, 0.85909569, 0.85173502])

Last model is the bes over all the previous models.